config/routes.rb
FacebookQuizzes::Application.routes.draw do

  root to: 'facebook#login'
  post '/' => 'facebook#login'
  get '/retake' => 'quizzes#retake'

  resources :quizzes do
    resources :categories, :answers
    resources :questions do
      post 'respond', on: :member
    end
    get 'finish'
    get 'start'
  end

  resources :questions do
    resources :answers
  end

  resources :answers

  resources :categories do
    resources :answers
  end

  get 'quizzes/:slug/:category_slug' => 'quizzes#result'

  

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
    @quiz = Quiz.new
  end

  def index
    @quizzes = Quiz.all
  end

  def edit
    @quiz = Quiz.from_param(params[:id])
    @question = Question.new
    @answer = Answer.new
    @category = Category.new
  end

  def update
    @quiz = Quiz.from_param params[:id]
    @quiz.update quiz_params
    @quiz.save!
    redirect_to edit_quiz_url(@quiz)
  end

  def show
    @quiz = Quiz.from_param params[:id]
  end

  def create
    quiz = Quiz.create(quiz_params)
    quiz.save!
    redirect_to edit_quiz_url(quiz)
  end

  def start
    @quiz = Quiz.from_param(params[:quiz_id])
    clear_session
    redirect_to @quiz.questions.first
  end

  def finish
    @quiz = Quiz.find_by_id params[:quiz_id]
    @category = @quiz.get_results(answers)
    redirect_to "/#{@quiz.slug}_#{@category.slug}"
  end

  def result
    @quiz = Quiz.find_by_slug(params["slug"])
    unless redirect_to_start?
      @category = @quiz.categories.find_by_slug params["category_slug"]
      render template: "quizzes/finish"
    else
      redirect_to "https://apps.facebook.com/aloette-quizzes"
    end
  end

  def retake
    @quiz = Quiz.last
    redirect_to @quiz
  end

  private
    def redirect_to_start?
      return false if Rails.env.development?
      return false if is_facebook?
      return true if has_answers?
      return false
    end

    def is_facebook?
      return true if request.user_agent =~ /facebookexternalhit/
      return true if request.user_agent =~ /Facebot/
      return false
    end

    def has_answers?
      answers.length.zero?
    end

    def answers
      session.to_hash.keep_if{|k, v| k.match(/question/)}
    end

    def quiz_params
      params.require(:quiz).permit(:name, :intro, :title, :product_copy)
    end

    def clear_session
      session.to_hash.keep_if{|k, v| k =~ /question_/ }.each{|k, v| session.delete(k) }
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def slug
    @quiz.slug.underscore
  end
end

app/views/quizzes/_categories.html.slim
#categories.row
  h2 Categories
  .edit
    - for category in @quiz.categories
      = form_for(category, html: { role: "form", class: "form-inline" }) do |f|
        .form-group
          = f.text_field :title, class: "form-control title"
          a.update href="/quizzes/#{@quiz.slug}/#{category.slug}" = "/quizzes/#{@quiz.slug}/#{category.slug}"
          .buttons
            = f.submit "Update", class: "btn btn-default"
            = link_to "Delete", category, method: :delete, class: "btn btn-default delete"
          .clear
          .second-row
            = f.text_field :statement, class: "form-control statement", placeholder: "Enter the category announcement"
  .new
    = form_for([@quiz, @category], html: { role: "form", class: "form-inline" }) do |f|
      .form-group
        = f.text_field :title, class: "form-control title", placeholder: "Short name"
        = f.submit 'Create New Category', class: "btn btn-default create"

app/views/quizzes/_details.html.slim
.row#details
  = form_for(@quiz, html: { role: "form", class: "form-inline" }) do |f|
    .form-group
      = f.text_field :name, class: 'form-control'
      = f.submit 'Update', class: "btn btn-default", text: "Update"
      = link_to "View", @quiz, class: "form-control btn btn-default"
    .clear
    .form-group.quiz-text-group
      .intro.textarea-label Quiz Intro
      = f.text_area :intro, class: 'form-control'

app/views/quizzes/_header.html.slim
#header = image_tag "#{slug}/header.jpg"

app/views/quizzes/_images.html.slim
#images
  .row
    h2 Images
    .edit-block
      img class="product" src=@quiz.product_img.url
      = form_for @quiz do |f|
        .form-group
          = f.file_field :product_img, class: "form-control"
          = f.submit "Change", class: "form-control"
    .edit-block
      img class="banner" src=@quiz.banner.url
      = form_for @quiz do |f|
        .form-group
          = f.file_field :banner, class: "form-control"
          = f.submit "Change", class: "form-control"

app/views/quizzes/_questions.html.slim
#questions.row
  h2 Questions + Answers
  .edit
    - for question in @quiz.questions
      = form_for(question, html: { role: "form", class: "form-inline details" }) do |f|
        = f.text_field :sequence, class: 'form-control seq', placeholder: "Seq."
        = f.text_field :weight, class: 'form-control weight', placeholder: "Wt."
        = f.text_field :text, class: 'form-control text'
        = f.submit 'Update', class: "btn btn-default"
        = link_to "Delete", question, class: "form-control btn btn-default delete-question", method: :delete
      - for answer in question.answers
        = form_for(question.answer_from_category(answer.category), html: { role: "form", class: "form-inline answer" } ) do |f|
          .form-group
            span.form-control-static.category = answer.category.title
            = f.text_field :sequence, class: 'form-control seq', placeholder: "Seq."
            = f.text_field :content, class: 'form-control content', placeholder: "Enter text for answer"
            = f.hidden_field(:category, value: answer.category.id)
            = f.hidden_field(:question_id, value: question.id)
            = f.submit 'Edit', class: "btn btn-default"
  #new
    = form_for([@quiz, @question], html: { role: "form", class: "form-inline" }) do |f|
      = f.text_field :text, class: 'form-control text', id: 'new-question', placeholder: "Enter text for new question"
      = f.submit 'Create', class: "btn btn-default"

app/views/quizzes/edit.html.slim
.container#quiz-edit
	.header.row
	  .heading Quiz Details
	  .back-link = link_to "Back to main", :quizzes
	== render 'details'
	== render 'questions'
	== render 'categories'

app/views/quizzes/finish.html.slim
= content_for :title do
  title = @category.statement
= content_for :head do
  = render "#{slug}/facebook_tags"
#container.center
  == render "header"
  == render "#{slug}/finish"

app/views/quizzes/index.html.slim
h1 Quiz View

- for quiz in @quizzes
	= link_to quiz.name, [:edit, quiz]
	div = quiz.intro

= link_to "New Quiz", new_quiz_path

app/views/quizzes/new.html.slim
h1 Create new quiz

= form_for @quiz, url: quizzes_path, html: { multipart: true } do |f|
	div = f.label :name
	div = f.text_field :name
	div = f.label :title
	div = f.text_field :title
	div = f.label :intro
	div = f.text_area  :intro
	div = f.submit

app/views/quizzes/show.html.slim
html
  head
  body
    #container.center
      - if @quiz.nil?
        | No quizzes!
      - else
        == render "header"
        == render "#{slug}/intro"